version: '0.1'
services:
  web:
    build: .
    ports:
     - "8000:80"
  postgres:
    image: postgres
    ports:
    -"5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: cs2018

    php:
        build: php
        expose:
            - 9000
        volumes:
            - ./php/www:/var/www/html

    apache2:
        image: webdevops/apache:latest
        args:
            - PHP_SOCKET=php:9000
        volumes:
            - ./php/www:/var/www/html
        ports:
            - 80:80
            - 443:443
        links:
            - php

