{
    "version": "3",
    "volumes": {
        "postgres_data": {},
    },
    "services": {
        "postgres": {
            "image": "postgres:alpine",
            "volumes": [
                "postgres_data:/var/lib/postgresql/data/"
            ],
            "environment": {
                "POSTGRES_PASSWORD": "cs2018",
                "POSTGRES_DB": "musicmatcher",
                "POSTGRES_USER" : "postgres"
            },
            "ports" : ["127.0.0.1:5433:5432"]
        },
        "backend": {
            "build" : {
                "context" : "../",
                "dockerfile": "docker/Dockerfile-apache-audiveris"
            },
            "volumes": [
                "../src:/var/www/html/"
            ],
            "ports": [
                "127.0.0.1:80:80"
            ],
            "depends_on": [
                "postgres",
            ]
        }
    }
}
