# Latest Ubuntu with Java 8, Apache2, PHP, tesseract, audiveris
# Build image with:  $	docker build -t musicmatcher .
# Run image with:  $ docker run  -p 8000:80 -v /home/tobias/mygits/musicmatcher/src/:/var/www/html/ musicmatcher
# use -d flag to run in background
# stop with $ sudo docker stop $(docker ps -a -q) 

FROM ubuntu:latest
LABEL authors="Tobias Wenzel, Pavel Brodianskyi"



# -------------------------------------------------------------
## install java 8 and it's dependecies
# -------------------------------------------------------------

ENV TZ Europe/Berlin	
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
    apt-get clean

# -------------------------------------------------------------
## install the webserver & php
## & move project files to web-server dir
# -------------------------------------------------------------

RUN  apt-get install apache2 php7.2 php7.2-gd -y

COPY src/ /var/www/html
COPY test_files /home/docker

RUN chown -R www-data:www-data /var/www/html/
RUN chown -R www-data:www-data /home/docker/out
RUN chown -R www-data:www-data /home/docker/res
RUN chmod -R 770 /home/docker/out
# -------------------------------------------------------------
## tesseract
## ->  also needed for Audiveris
# -------------------------------------------------------------

RUN apt-get install libfreetype6-dev -y && \
 apt-get install tesseract-ocr tesseract-ocr-deu tesseract-ocr-eng tesseract-ocr-fra  -y 



RUN apt-get install git -y
# -------------------------------------------------------------
## Install Audiveris & it's dependencies
# -------------------------------------------------------------


COPY /docker/backend/ /home/docker
RUN cd /home/docker/audiveris && \
 export TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/ && \
  ./gradlew clean build 

## move compiled program & remove old files
RUN tar -xf /home/docker/audiveris/build/distributions/Audiveris.tar -C /home/docker
RUN rm -rf /home/docker/audiveris


# -------------------------------------------------------------
## crop notes
# -------------------------------------------------------------

RUN apt-get install -y libpng-dev

# -------------------------------------------------------------
# grant permission for file editing
# -------------------------------------------------------------



RUN chown www-data:www-data -R /home/docker/Audiveris


# not sure if we need this
RUN apt-get install sudo
RUN adduser www-data sudo
RUN echo 'www-data ALL=(user) NOPASSWD: /home/docker/Audiveris/bin/Audiveris' >> /etc/sudoers



CMD apachectl -D FOREGROUND
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

# echo "TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/" >> /etc/environment 
ENV TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/
ENV HOME=/home/docker
# grant port access
EXPOSE 80



