FROM php:apache

RUN apt-get update \
  && apt-get install --yes --no-install-recommends libpq-dev \
  && docker-php-ext-install pdo_pgsql 

RUN apt-get install libpng-dev -y
RUN docker-php-ext-install gd
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

