# Latest Ubuntu with Java 8, Apache2, PHP, tesseract, audiveris
# Build image with:  $	docker build -t musicmatcher .
# Run image with:  $ docker run  -p 8000:80 -v /home/tobias/mygits/musicmatcher/src/:/var/www/html/ musicmatcher
# use -d flag to run in background
# stop with $ sudo docker stop $(docker ps -a -q) 

FROM ubuntu:latest
LABEL authors="Tobias Wenzel, Pavel Brodianskyi"

# -------------------------------------------------------------
## install java 8 and it's dependecies
# -------------------------------------------------------------

ENV TZ Europe/Berlin	
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
    apt-get clean
RUN apt-get install git -y

# -------------------------------------------------------------
## tesseract
## ->  also needed for Audiveris
# -------------------------------------------------------------

RUN apt-get update && \
 apt-get install libfreetype6-dev -y && \
 apt-get install tesseract-ocr tesseract-ocr-deu tesseract-ocr-eng tesseract-ocr-fra  -y 

# echo "TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/" >> /etc/environment 
ENV TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/


# -------------------------------------------------------------
## Install Audiveris & it's dependencies
# -------------------------------------------------------------


COPY backend/ /home/docker
RUN cd /home/docker/audiveris && \
 export TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/ && \
  ./gradlew clean build 

## move compiled program 
RUN tar -xf /home/docker/audiveris/build/distributions/Audiveris.tar -C /home/docker
RUN rm -rf /home/docker/audiveris


# -------------------------------------------------------------
# grant permission for file editing
# -------------------------------------------------------------


#RUN chown -R www-data:www-data /var/www/html/
#RUN chown -R www-data:www-data /var/www/html/out
#RUN chown -R www-data:www-data /var/www/html/res
#RUN chmod -R 770 /var/www/html/out


# this is necessesaray to run apache2
# not sure if we need this
#RUN apt-get install sudo
#RUN adduser www-data sudo
#RUN echo 'www-data ALL=(user) NOPASSWD: /home/docker/Audiveris/bin/Audiveris' >> /etc/sudoers
#RUN chown www-data:www-data -R /home/Audiveris





